# Generated by Django 5.1.4 on 2024-12-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('tests_tests', '0005_remove_testresult_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpost',
            name='quiz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='tests_tests.test'),
        ),
    ]
