# Generated by Django 5.1.4 on 2024-12-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_assignmentpost_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentpost',
            old_name='quiz',
            new_name='test',
        ),
    ]
