# Generated by Django 5.1.4 on 2024-12-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_questions', '0004_remove_question_type_and_more'),
        ('tests_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='tests_questions.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
