# Generated by Django 5.1.4 on 2024-12-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_tests', '0003_testattempt_current_question_alter_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_tests.testattempt'),
        ),
    ]
