# Generated by Django 5.1.4 on 2024-12-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_tests', '0004_alter_testresult_test_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='feedback',
        ),
    ]
