# Generated by Django 5.1.4 on 2025-03-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_answers', '0001_initial'),
        ('tests_questions', '0001_initial'),
        ('tests_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_questions.question'),
        ),
        migrations.AddField(
            model_name='answerorder',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_orders', to='tests_answers.answer'),
        ),
        migrations.AddField(
            model_name='answerorder',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_orders', to='tests_tests.testattempt'),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_questions.question'),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_answers.answer'),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tests_tests.testattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='answerorder',
            unique_together={('test_attempt', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='answerresponse',
            unique_together={('test_attempt', 'question')},
        ),
    ]
