# Generated by Django 5.1.4 on 2024-12-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_answers', '0001_initial'),
        ('tests_questions', '0003_initial'),
        ('tests_tests', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerresponse',
            unique_together={('test_attempt', 'question')},
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_answers.answer'),
        ),
        migrations.RemoveField(
            model_name='answerresponse',
            name='selected_answers',
        ),
        migrations.RemoveField(
            model_name='answerresponse',
            name='user_answer_text',
        ),
        migrations.CreateModel(
            name='AnswerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_orders', to='tests_answers.answer')),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_orders', to='tests_tests.testattempt')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test_attempt', 'answer')},
            },
        ),
    ]
