# Generated by Django 5.1.4 on 2024-12-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_questions', '0001_initial'),
        ('tests_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_tests.test'),
        ),
        migrations.AddField(
            model_name='questionorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_orders', to='tests_questions.question'),
        ),
        migrations.AddField(
            model_name='questionorder',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_orders', to='tests_tests.testattempt'),
        ),
    ]
