# Generated by Django 5.1.4 on 2024-12-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_questions', '0003_initial'),
        ('tests_tests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='questionorder',
            unique_together={('test_attempt', 'question')},
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='user',
        ),
    ]
