# Generated by Django 5.1.4 on 2024-12-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-channel-image.svg', upload_to='channels/image')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visits_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
